blueprint:
  name: Copycat Crew
  description: Synchronize the state of followers with the leader.
  domain: automation
  input:
    leader:
      name: Leader
      description: Select the leader entity.
      selector:
        entity:
          domain:
            - switch
            - light
            - sensor
            - input_select
            - input_boolean
    followers:
      name: Followers
      description: Select the follower entities.
      selector:
        entity:
          domain:
            - switch
            - light
            - sensor
            - input_select
            - input_boolean
          multiple: true

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input leader

action:
  - service_template: >
      {% if trigger.to_state.state == 'on' %}
        homeassistant.turn_on
      {% else %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id: !input followers
