blueprint:
  name: HVAC Pause
  description: Pauses HVAC when windows/doors open; resumes last state once closed
  domain: automation

  input:
    humidifier_device:
      description: Climate entity used for climate control.
      name: Climate Device
      selector:
        entity:
          domain: humidifier

    doors_windows:
      description: Group of entities that will activate automation. (Assumes 'on' means 'open')
      name: Door and window sensors.
      selector:
        entity:
          domain:
            - group
            - binary_sensor

    pause_delay:
      description: Time to wait before pausing the HVAC system.
      name: Pause Delay
      default:
        hours: 00
        minutes: 05
        seconds: 00
      selector:
        duration:

    resume_delay:
      description: Time to wait before resuming the HVAC system.
      name: Resume Delay
      default:
        hours: 00
        minutes: 00
        seconds: 30
      selector:
        duration:

mode: single
trigger:
  - platform: state
    entity_id: !input doors_windows
    from: "off"
    to: "on"
    for: !input pause_delay
    id: group_open
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: !input humidifier_device
        state: "off"
action:
  - service: humidifier.turn_off
    target:
      entity_id: !input humidifier_device
  - wait_for_trigger:
      - platform: state
        entity_id: !input doors_windows
        from: "on"
        to: "off"
        for: !input resume_delay
    continue_on_timeout: false
