blueprint:
  name: Humidity Hero
  description: >
    # Humidity Hero

    Pauses the humidifier when windows or doors are open. Once the windows or doors are closed, the humidifier will resume its previous state.

    This automation can be useful for preventing excess humidity in a room when it is being ventilated, such as when opening a window on a rainy day. The pause and resume delays can be customized to suit your preferences.

    ## Inputs

     - **humidifier_device**: Climate entity used for climate control.
     - **doors_windows**: Group of entities that will activate automation. (Assumes 'on' means 'open')
     - **pause_delay**: Time to wait before pausing the humidifier.
     - **resume_delay**: Time to wait before resuming the humidifier.

  domain: automation

  input:
    humidifier_device:
      description: Humidifier/Dehumidifier entity used for climate control.
      name: Humidifier/Dehumidifier Device
      selector:
        entity:
          domain: humidifier

    doors_windows:
      description: Group of entities that will activate automation. (Assumes 'on' means 'open')
      name: Door and window sensors.
      selector:
        entity:
          domain:
            - group
            - binary_sensor

    pause_delay:
      description: Time to wait before pausing the Humidifier/Dehumidifier.
      name: Pause Delay
      default:
        hours: 00
        minutes: 05
        seconds: 00
      selector:
        duration:

    resume_delay:
      description: Time to wait before resuming the Humidifier/Dehumidifier.
      name: Resume Delay
      default:
        hours: 00
        minutes: 00
        seconds: 30
      selector:
        duration:

mode: single
trigger:
  - platform: state
    entity_id: !input doors_windows
    from: "off"
    to: "on"
    for: !input pause_delay
    id: group_open
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: !input humidifier_device
        state: "off"
action:
  - service: humidifier.turn_off
    target:
      entity_id: !input humidifier_device
  - wait_for_trigger:
      - platform: state
        entity_id: !input doors_windows
        from: "on"
        to: "off"
        for: !input resume_delay
    continue_on_timeout: false
