blueprint:
  name: Humidity Hero
  description: Turn off the hygrostat when humidity falls below a certain threshold or windows are open.
  domain: automation

inputs:
  switch:
    name: Hygrostat Switch
    description: The entity ID of the hygrostat switch.
    selector:
      entity:
  sensor:
    name: Humidity Sensor
    description: The entity ID of the humidity sensor.
    selector:
      entity:
  binary_sensor:
    name: Window Binary Sensor
    description: The entity ID of the window binary sensor.
    selector:
      entity:
  below:
    name: Humidity Threshold
    description: The humidity threshold at which the hygrostat should be turned off.
    selector:
      number:

triggers:
  - event: state_changed
    entity_id: '{{ input.sensor }}'
    to: '{{ trigger.below }}'
  - event: state_changed
    entity_id: '{{ input.binary_sensor }}'
    to: 'on'

actions:
  - service: switch.turn_off
    entity_id: '{{ input.switch }}'

conditions:
  - condition: template
    value_template: '{{ states[input.sensor].state | int < trigger.below }}'
  - condition: state
    entity_id: '{{ input.binary_sensor }}'
    state: 'on'

variables:
  below: '{{ input.below }}'
