blueprint:
  name: Hygrostat
  description: Turn off the hygrostat when humidity falls below a certain threshold or windows are open.
  domain: automation

triggers:
  - event: state_changed
    entity_id: '{{ inputs.sensor }}'
    to: '{{ trigger.below }}'
  - event: state_changed
    entity_id: '{{ inputs.binary_sensor }}'
    to: 'on'

actions:
  - service: switch.turn_off
    entity_id: '{{ inputs.switch }}'

conditions:
  - condition: template
    value_template: '{{ states[inputs.sensor].state | int < trigger.below }}'
  - condition: state
    entity_id: '{{ inputs.binary_sensor }}'
    state: 'on'

inputs:
  switch:
    description: The entity ID of the hygrostat switch.
    type: string
  sensor:
    description: The entity ID of the humidity sensor.
    type: string
  binary_sensor:
    description: The entity ID of the window binary sensor.
    type: string
  below:
    description: The humidity threshold at which the hygrostat should be turned off.
    type: integer

variables:
  below: 30
