blueprint:
  name: Incremental Temperature Control
  description: 'Automatically adjust temperature incrementally from current temperature to target temperature.'

  domain: automation
  input:
    climate_entity:
      name: Climate Entity
      description: The climate device to control.
      selector:
        entity:
          domain: climate

mode: restart

trigger:
  platform: state
  entity_id: !input 'climate_entity'
condition: []
variables:
  target_temp: "{{ state_attr(trigger.entity_id, 'temperature') }}"
  current_temp: "{{ trigger.to_state.attributes.current_temperature }}"
  step_temp: 1

action:
  - repeat:
      while:
        - condition: template
          value_template: "{{ state_attr(trigger.entity_id, 'temperature') != target_temp }}"
      sequence:
        - service: climate.set_temperature
          target:
            entity_id: !input 'climate_entity'
          data:
            temperature: "{{ state_attr(trigger.entity_id, 'temperature') + step_temp }}"
        - delay: '00:00:01'
