blueprint:
  name: SMAL – Smart Motion-Activated Lighting (Device/Area Selector)
  description: >
    # Introduction

    The "Smart Motion-Activated Lighting" blueprint creates an automation that turns on lights or devices when motion is detected. It has several optional features that allow users to customize the automation's behavior based on their needs.

    ## Optional Features
    Some examples of how the optional features can be used include:
    - Defining different devices/areas for different times of day (e.g., bright lights for daytime and dim lights for nighttime)
    - Activating devices during a specified time frame (e.g., turn on lights from 6 pm to 10 pm)
    - Only running the automation if certain entities are in a desired state (e.g., only running if the house is unoccupied)

    ## Capabilities
    - Triggers on motion (can be triggered by anything that switches between "on" and "off")
    - Wait time for turning off lights/devices
    - Optional feature to only run if certain entities are in a desired state
    - Optional feature to check sun elevation
    - Optional feature for defining devices/areas for different times of day
    - Optional feature for a default state when motion stops
    - Optional "no motion blocker" with user-specified state
    - Inputs for motion sensor entity, light/device/area selector

  domain: automation
  source_url: https://gist.github.com/networkingcat/a1876d7e706e07c8bdcf974113940fb8
  input:
    motion_entity:
      name: Motion Sensor
      description: Motion Sensor or a group with Motion Sensors (But can be anything switching between "on" and "off")
      selector:
        entity:
    device_area_selector:
      name: Light/Device/Area Selector
      selector:
        target:
          entity:

    no_motion_wait:
      name: Wait time
      description: Time to leave the light/device on after the last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    automation_blocker:
      name: Automation Blocker (Optional)
      description: Only run if this boolean is in the desired state (see next input)
      default:
      selector:
        entity:
    automation_blocker_boolean:
      name: Automation Blocker Chooser (Optional)
      description: Desired state of automation blocker, choose "on" for on and "off" for off
      default: false
      selector:
        boolean:
    no_motion_blocker:
      name: No Motion Blocker (Optional)
      description: No motion sequence is not run if this boolean is in the desired state (see next input)
      default:
      selector:
        entity:
    no_motion_blocker_boolean:
      name: No Motion Chooser (Optional)
      description: Desired state of no motion blocker, choose "on" for on and "off" for off
      default: false
      selector:
        boolean:
    elevation_check:
      name: Sun elevation check (Optional)
      description: This is the angle between the sun and the horizon. Negative values mean the sun is BELOW the horizon.
      default: none
      selector:
        number:
          min: -90
          max: 90
          unit_of_measurement: degrees

    time_device_area_start:
      name: Device/Area Activation Start Time (Optional)
      description: Time from which the device/area will be activated if motion is detected.
      default: "00:00:00"
      selector:
        time:
    time_device_area_end:
      name: Device/Area Activation End Time (Optional)
      description: Time from which the device/area will be deactivated if motion is detected.
      default: "00:00:00"
      selector:
        time:
    device_area_no_motion:
      name: Default state for no motion (Optional)
      description: Set this state if you want to activate a specific state if motion stops
      default: "off"
      selector:
        entity:
